-- ==========================================
-- 200 LIFE & RELATIONSHIP DEPTH QUESTIONS
-- Covers the important life topics every
-- couple should talk about openly.
-- ==========================================
-- Categories: Family & Future, Conflict & Repair,
--             Mental Health, Work & Balance,
--             Love Languages, Social Life,
--             Health & Wellness, Meaning & Purpose,
--             This or That, Relationship Pulse

INSERT INTO questions (text, category) VALUES

-- ===== FAMILY & FUTURE (25) =====
('Do you want children someday, and if so, how many feels right to you?', 'Family & Future'),
('What kind of parent do you think you would be?', 'Family & Future'),
('What is one thing from how you were raised that you definitely want to repeat?', 'Family & Future'),
('What is one thing from your upbringing you would do completely differently?', 'Family & Future'),
('How do you feel about the role our extended families play in our life?', 'Family & Future'),
('What boundaries with in-laws or family members are important to you?', 'Family & Future'),
('How would you want us to handle disagreements about parenting?', 'Family & Future'),
('What does a healthy relationship with your parents look like to you right now?', 'Family & Future'),
('If we had kids, what values would be most important for us to teach them?', 'Family & Future'),
('How do you feel about holidays — whose family do we visit and when?', 'Family & Future'),
('What is your honest feeling about the timeline for starting a family?', 'Family & Future'),
('How involved do you want grandparents to be if we have children?', 'Family & Future'),
('What family dynamic from a friend or relative do you admire?', 'Family & Future'),
('How do you feel about adopting or fostering children?', 'Family & Future'),
('What would you want our family traditions to look like?', 'Family & Future'),
('How do you imagine our life changing if we become parents?', 'Family & Future'),
('What are your thoughts on how to divide parenting responsibilities?', 'Family & Future'),
('How do you feel about the pressure from family or society to have children?', 'Family & Future'),
('What is one thing you want our kids to know about our relationship?', 'Family & Future'),
('How would you want to handle it if a family member oversteps a boundary?', 'Family & Future'),
('What scares you most about the idea of becoming a parent?', 'Family & Future'),
('What excites you most about the idea of building a family together?', 'Family & Future'),
('How do you feel about screen time, discipline, and education for future kids?', 'Family & Future'),
('If we could not have biological children, how would you feel about alternatives?', 'Family & Future'),
('What kind of home environment do you want to create for our future family?', 'Family & Future'),

-- ===== CONFLICT & REPAIR (25) =====
('How do you typically react in the first moments of a disagreement?', 'Conflict & Repair'),
('Do you prefer to address conflict immediately or take time to cool down first?', 'Conflict & Repair'),
('What is your biggest trigger during an argument?', 'Conflict & Repair'),
('What does a genuine apology look like to you?', 'Conflict & Repair'),
('How do you know when a conflict between us is truly resolved?', 'Conflict & Repair'),
('What is something I do during arguments that actually helps?', 'Conflict & Repair'),
('What is something I do during arguments that makes things worse?', 'Conflict & Repair'),
('How do you feel about going to bed angry?', 'Conflict & Repair'),
('What does repair look like for you after we have had a fight?', 'Conflict & Repair'),
('Do you feel like we fight fairly, or is there something we should change?', 'Conflict & Repair'),
('What is the hardest thing for you to say during a disagreement?', 'Conflict & Repair'),
('How do you feel about taking a break mid-argument to collect your thoughts?', 'Conflict & Repair'),
('What tone of voice or body language from me helps you feel heard during conflict?', 'Conflict & Repair'),
('Is there a past argument that still feels unresolved for you?', 'Conflict & Repair'),
('How do you want me to approach you when I am upset about something?', 'Conflict & Repair'),
('What is the difference between a healthy disagreement and a harmful fight for you?', 'Conflict & Repair'),
('How do you feel about revisiting the same issue if it keeps coming up?', 'Conflict & Repair'),
('What helps you forgive after you have been hurt?', 'Conflict & Repair'),
('Do you ever shut down during conflict, and if so, what do you need in that moment?', 'Conflict & Repair'),
('How can we make sure small annoyances do not build into big resentments?', 'Conflict & Repair'),
('What was the best way we ever resolved a disagreement?', 'Conflict & Repair'),
('How do you feel about couples therapy as a tool for conflict resolution?', 'Conflict & Repair'),
('What phrase or gesture from me would help de-escalate a tense moment?', 'Conflict & Repair'),
('How long does it usually take you to feel reconnected after a fight?', 'Conflict & Repair'),
('What is one rule you think we should always follow during disagreements?', 'Conflict & Repair'),

-- ===== MENTAL HEALTH (20) =====
('How are you really doing mentally and emotionally right now?', 'Mental Health'),
('What does anxiety look like for you, and how can I recognize it?', 'Mental Health'),
('What is the most helpful thing I can do when you are going through a hard time?', 'Mental Health'),
('How do you feel about asking for professional help when things get heavy?', 'Mental Health'),
('What drains your mental energy the fastest?', 'Mental Health'),
('What recharges your emotional batteries when they are running low?', 'Mental Health'),
('How do you want me to check in on your mental health without it feeling intrusive?', 'Mental Health'),
('Is there something you are carrying emotionally that I might not know about?', 'Mental Health'),
('How do you feel about talking about sadness or low periods openly with me?', 'Mental Health'),
('What does a mentally healthy week look like for you?', 'Mental Health'),
('How can we create a home environment that supports both our mental health?', 'Mental Health'),
('What coping mechanisms work well for you and which ones do not?', 'Mental Health'),
('How do you feel about our balance of being each other''s support versus seeking outside help?', 'Mental Health'),
('What is the most emotionally exhausting thing in your life right now?', 'Mental Health'),
('How do you want me to respond when you say you are fine but clearly are not?', 'Mental Health'),
('What role does sleep play in your mental health?', 'Mental Health'),
('How do you handle overthinking, and how can I help?', 'Mental Health'),
('What past experience still affects your mental health today?', 'Mental Health'),
('How do you feel about setting boundaries to protect your own well-being?', 'Mental Health'),
('What would you want our relationship to feel like on your worst mental health days?', 'Mental Health'),

-- ===== WORK & BALANCE (20) =====
('How fulfilled are you in your current job or career?', 'Work & Balance'),
('What does a good work-life balance look like for you?', 'Work & Balance'),
('How can I better support your career ambitions?', 'Work & Balance'),
('Do you feel like work takes up too much of our time together?', 'Work & Balance'),
('What is a career dream you have that you have not fully pursued yet?', 'Work & Balance'),
('How do you feel about bringing work stress home?', 'Work & Balance'),
('What would you do professionally if success was guaranteed?', 'Work & Balance'),
('How do you want us to handle it when one of us has an intense work period?', 'Work & Balance'),
('Do you feel supported enough in your professional life by me?', 'Work & Balance'),
('How would you feel about one of us taking a big career risk?', 'Work & Balance'),
('What boundaries between work and personal life are most important to you?', 'Work & Balance'),
('How do you feel about working from home versus going to an office?', 'Work & Balance'),
('What would your ideal work schedule look like?', 'Work & Balance'),
('How do you handle a bad day at work, and what do you need from me?', 'Work & Balance'),
('Do you ever feel like you have to choose between career success and relationship time?', 'Work & Balance'),
('What accomplishment at work are you most proud of?', 'Work & Balance'),
('How do you feel about our current division of household tasks versus work?', 'Work & Balance'),
('If you could take a sabbatical, what would you do with it?', 'Work & Balance'),
('What part of your job energizes you, and what part drains you?', 'Work & Balance'),
('Where do you see your career in five years, and how does our relationship fit in?', 'Work & Balance'),

-- ===== LOVE LANGUAGES (20) =====
('What specific action from me makes you feel most loved on an ordinary day?', 'Love Languages'),
('Do you feel more loved through words, touch, quality time, acts of service, or gifts?', 'Love Languages'),
('What is a small daily gesture that would mean the world to you?', 'Love Languages'),
('When was the last time you felt deeply appreciated by me?', 'Love Languages'),
('How do you prefer to receive compliments — publicly or privately?', 'Love Languages'),
('What chore or task would feel like an act of love if I did it without being asked?', 'Love Languages'),
('What kind of quality time fills your cup the most?', 'Love Languages'),
('How important is physical affection throughout the day — not just in intimate moments?', 'Love Languages'),
('Do you feel loved when I plan something for us, or when I join something you planned?', 'Love Languages'),
('What is a way of showing love that you wish you received more of?', 'Love Languages'),
('How do you feel about surprise gifts versus practical ones?', 'Love Languages'),
('What makes you feel taken for granted, and what is the opposite of that?', 'Love Languages'),
('Do you feel more loved when I tell you or when I show you?', 'Love Languages'),
('What is the most meaningful text or note I have ever sent you?', 'Love Languages'),
('How do you most naturally express love, and is it the same way you want to receive it?', 'Love Languages'),
('What is something I used to do more of that made you feel cherished?', 'Love Languages'),
('How do you feel about random hugs, hand-holding, and small touches in public?', 'Love Languages'),
('What does a day where you feel completely loved look like from morning to night?', 'Love Languages'),
('Is there a way I try to show love that does not quite land for you?', 'Love Languages'),
('What is the love language you think I need most that you could work on giving?', 'Love Languages'),

-- ===== SOCIAL LIFE (20) =====
('How do you feel about the amount of time we spend with friends versus alone together?', 'Social Life'),
('Is there a friendship of mine that you find difficult, and why?', 'Social Life'),
('How important is it for you that we have couple friends?', 'Social Life'),
('Do you feel like you have enough time for your own friendships?', 'Social Life'),
('How do you feel about spending time apart with your own friends?', 'Social Life'),
('Is there a social situation I put you in that makes you uncomfortable?', 'Social Life'),
('How do you want to handle it when one of us wants to go out and the other wants to stay in?', 'Social Life'),
('Do you feel like I represent us well when we are around other people?', 'Social Life'),
('How do you feel about posting about our relationship on social media?', 'Social Life'),
('What is your ideal weekend balance between social plans and downtime?', 'Social Life'),
('How do you feel when I talk about our relationship with my friends?', 'Social Life'),
('Is there someone you have lost touch with that you wish you had not?', 'Social Life'),
('How do you feel about hosting people at our home?', 'Social Life'),
('Do you consider yourself more introverted or extroverted, and how should that shape our plans?', 'Social Life'),
('How do you feel about me maintaining friendships with exes?', 'Social Life'),
('What kind of social events do you actually enjoy versus tolerate?', 'Social Life'),
('How do you want us to handle it if one of us does not like the other''s friend?', 'Social Life'),
('Is there a friendship you want to invest more in right now?', 'Social Life'),
('How do you feel about double dates compared to solo couple time?', 'Social Life'),
('What social boundary is most important for you in our relationship?', 'Social Life'),

-- ===== HEALTH & WELLNESS (20) =====
('How do you feel about your body and physical health right now?', 'Health & Wellness'),
('What health goal would you like us to work toward together?', 'Health & Wellness'),
('How important is exercise in your life, and how can I support that?', 'Health & Wellness'),
('What does your ideal morning routine for health and wellness look like?', 'Health & Wellness'),
('How do you feel about our eating habits as a couple?', 'Health & Wellness'),
('Is there a health habit you want to build but struggle to maintain?', 'Health & Wellness'),
('How much sleep do you actually need to feel your best?', 'Health & Wellness'),
('What is your relationship with alcohol, and are you happy with it?', 'Health & Wellness'),
('How do you feel about going to the doctor for regular checkups?', 'Health & Wellness'),
('What physical activity would you enjoy doing together regularly?', 'Health & Wellness'),
('How does your physical health affect your mood and our relationship?', 'Health & Wellness'),
('What is one healthy change you have been meaning to make?', 'Health & Wellness'),
('How do you feel about cooking healthy meals together versus convenience food?', 'Health & Wellness'),
('What role does nature and being outdoors play in your well-being?', 'Health & Wellness'),
('How do you want to handle it when one of us is sick or in pain?', 'Health & Wellness'),
('What does rest actually look like for you — is it sleep, quiet, or something else?', 'Health & Wellness'),
('How do you feel about our screen time habits as a couple?', 'Health & Wellness'),
('Is there a health concern you have been putting off dealing with?', 'Health & Wellness'),
('How do you feel about meditation, journaling, or other mindfulness practices?', 'Health & Wellness'),
('What does aging well together look like to you?', 'Health & Wellness'),

-- ===== MEANING & PURPOSE (20) =====
('What gives your life the most meaning right now?', 'Meaning & Purpose'),
('Do you feel like you are living in alignment with your values?', 'Meaning & Purpose'),
('What is something bigger than yourself that you care deeply about?', 'Meaning & Purpose'),
('How do you feel about the role of spirituality or faith in your life?', 'Meaning & Purpose'),
('What legacy do you want to leave behind in this world?', 'Meaning & Purpose'),
('What is a cause or issue that you wish more people cared about?', 'Meaning & Purpose'),
('How do you find purpose on the days when everything feels mundane?', 'Meaning & Purpose'),
('What does a meaningful life look like to you versus a successful one?', 'Meaning & Purpose'),
('How do you feel about the balance between ambition and contentment?', 'Meaning & Purpose'),
('What question about life or existence do you think about most often?', 'Meaning & Purpose'),
('How has your sense of purpose changed over the years?', 'Meaning & Purpose'),
('What moment in your life made you feel like you were exactly where you were meant to be?', 'Meaning & Purpose'),
('How important is it to you that we share similar views on meaning and purpose?', 'Meaning & Purpose'),
('What do you think happens after we die, and how does that belief shape how you live?', 'Meaning & Purpose'),
('Is there a book, talk, or experience that fundamentally shaped your worldview?', 'Meaning & Purpose'),
('How do you feel about giving back — volunteering, donating, or mentoring?', 'Meaning & Purpose'),
('What brings you a sense of peace that nothing else does?', 'Meaning & Purpose'),
('Do you ever feel like something is missing, even when everything seems fine?', 'Meaning & Purpose'),
('What tradition or ritual gives your life structure and meaning?', 'Meaning & Purpose'),
('If you had one message to share with the world, what would it be?', 'Meaning & Purpose'),

-- ===== THIS OR THAT (15) =====
('Would you rather have a deep two-hour conversation or a fun adventure day with me?', 'This or That'),
('City apartment with a view or countryside house with a garden?', 'This or That'),
('Would you rather always know what I am thinking or always know what I am feeling?', 'This or That'),
('Surprise vacation planned by me or a trip we plan together?', 'This or That'),
('Would you rather have more time together or more money for experiences?', 'This or That'),
('Stay in with a movie and takeout or go out to a fancy dinner?', 'This or That'),
('Would you rather be told you are beautiful or that you are brilliant?', 'This or That'),
('One incredible vacation a year or several small weekend getaways?', 'This or That'),
('Would you rather know our future or be surprised by it?', 'This or That'),
('Early mornings together or late nights?', 'This or That'),
('Would you rather I cook for you or take you out?', 'This or That'),
('Big wedding or intimate elopement?', 'This or That'),
('Would you rather receive a handwritten letter or a spontaneous voice message?', 'This or That'),
('Routine and stability or constant novelty and change?', 'This or That'),
('Would you rather we had a shared hobby or each kept our own separate ones?', 'This or That'),

-- ===== RELATIONSHIP PULSE (15) =====
('How connected do you feel to me right now, on a scale of one to ten?', 'Relationship Pulse'),
('Is there anything between us that feels unfinished or unspoken?', 'Relationship Pulse'),
('What has been the best part of our relationship this week?', 'Relationship Pulse'),
('Is there something I did recently that really meant a lot to you?', 'Relationship Pulse'),
('How supported do you feel by me in your daily life right now?', 'Relationship Pulse'),
('Is there something you need from me that you are not getting enough of?', 'Relationship Pulse'),
('What is one thing we could improve about this week together?', 'Relationship Pulse'),
('Do you feel like we are growing closer or drifting apart lately?', 'Relationship Pulse'),
('What is one thing I did this week that made you smile?', 'Relationship Pulse'),
('How is our communication feeling to you these days?', 'Relationship Pulse'),
('Do you feel prioritized in my life right now?', 'Relationship Pulse'),
('What is something you are looking forward to with me?', 'Relationship Pulse'),
('Is there a conversation we need to have that we have been avoiding?', 'Relationship Pulse'),
('What could we do this weekend to feel more connected?', 'Relationship Pulse'),
('How happy are you in our relationship right now, honestly?', 'Relationship Pulse')

ON CONFLICT DO NOTHING;
