-- ==========================================
-- 200+ INTIMATE COUPLE QUESTIONS
-- Thoughtful questions about intimacy, desire,
-- boundaries, and sexual connection.
-- ==========================================
-- Categories: Desires & Fantasies, Preferences & Pleasure,
--             Communication & Trust, Intimacy & Connection,
--             Exploration, Boundaries & Comfort, Drive & Desire,
--             Romance & Foreplay, Growth & Discovery

INSERT INTO questions (text, category) VALUES

-- ===== DESIRES & FANTASIES (25) =====
('What is a sexual fantasy you have never shared with anyone before?', 'Desires & Fantasies'),
('Is there a scenario or role-play that has always intrigued you?', 'Desires & Fantasies'),
('What is something you have seen in a movie or read in a book that turned you on?', 'Desires & Fantasies'),
('If we could have an entire night with no rules or inhibitions, what would you want to happen?', 'Desires & Fantasies'),
('Is there a specific place you have always fantasized about being intimate?', 'Desires & Fantasies'),
('What is a fantasy you used to feel shy about but are more open to now?', 'Desires & Fantasies'),
('Do you ever have recurring sexual daydreams? What are they about?', 'Desires & Fantasies'),
('What would your ideal seduction scenario look like from start to finish?', 'Desires & Fantasies'),
('Is there a power dynamic that excites you — being in control, giving it up, or something in between?', 'Desires & Fantasies'),
('What kind of dirty talk, if any, turns you on the most?', 'Desires & Fantasies'),
('Have you ever fantasized about something and then realized you actually want to try it?', 'Desires & Fantasies'),
('What is a fantasy you enjoy thinking about but might not want to act on in real life?', 'Desires & Fantasies'),
('If we were to write our own intimate story together, what would the plot be?', 'Desires & Fantasies'),
('What type of lingerie or clothing do you find most arousing on me?', 'Desires & Fantasies'),
('Is there a time of day or setting that makes you feel most sexually imaginative?', 'Desires & Fantasies'),
('What is a fantasy that has evolved or changed since we have been together?', 'Desires & Fantasies'),
('If we had a hotel room for an entire weekend with nothing planned, what would you want us to do?', 'Desires & Fantasies'),
('Do you ever fantasize about moments from our past together? Which ones?', 'Desires & Fantasies'),
('What element of surprise turns you on the most in an intimate setting?', 'Desires & Fantasies'),
('Is there a specific outfit, look, or vibe of mine that lives rent-free in your fantasies?', 'Desires & Fantasies'),
('What is something subtle I could whisper to you that would drive you wild?', 'Desires & Fantasies'),
('Have you ever had a dream about us that was so good you wished it was real?', 'Desires & Fantasies'),
('What is one thing you would love me to initiate without asking?', 'Desires & Fantasies'),
('If we made a private bucket list for the bedroom, what would be the first three items?', 'Desires & Fantasies'),
('What is something you fantasize about that you think would surprise me?', 'Desires & Fantasies'),

-- ===== PREFERENCES & PLEASURE (25) =====
('What type of touch gives you the most pleasure?', 'Preferences & Pleasure'),
('Where on your body do you wish I paid more attention?', 'Preferences & Pleasure'),
('What is the one thing I do during sex that you absolutely love?', 'Preferences & Pleasure'),
('Do you prefer slow and sensual or more intense and passionate?', 'Preferences & Pleasure'),
('What kind of kissing turns you on the most?', 'Preferences & Pleasure'),
('Is there a position that always feels amazing for you?', 'Preferences & Pleasure'),
('How important is eye contact during intimacy for you?', 'Preferences & Pleasure'),
('What is your favorite way for us to build tension before we are actually intimate?', 'Preferences & Pleasure'),
('Do you enjoy being teased, and if so, how?', 'Preferences & Pleasure'),
('What part of foreplay do you enjoy the most?', 'Preferences & Pleasure'),
('How do you feel about using your hands versus your mouth versus toys?', 'Preferences & Pleasure'),
('What tempo and rhythm works best for you during sex?', 'Preferences & Pleasure'),
('Is there a specific area on your body that is an unexpected erogenous zone?', 'Preferences & Pleasure'),
('How do you feel about noise during sex — do you like it vocal or quiet?', 'Preferences & Pleasure'),
('What helps you reach orgasm most reliably?', 'Preferences & Pleasure'),
('Do you prefer to finish together or does the order not matter to you?', 'Preferences & Pleasure'),
('What is your favorite thing about how our bodies fit together?', 'Preferences & Pleasure'),
('How do you feel about massage as a transition into intimacy?', 'Preferences & Pleasure'),
('What kind of pressure and grip do you prefer when I touch you?', 'Preferences & Pleasure'),
('Is there a difference between what feels physically good and what feels emotionally connecting?', 'Preferences & Pleasure'),
('What do you enjoy most about giving pleasure to me?', 'Preferences & Pleasure'),
('How do you feel about quickies versus long, drawn-out sessions?', 'Preferences & Pleasure'),
('What is a technique I use that you would love me to do more often?', 'Preferences & Pleasure'),
('Do you prefer more focus on the buildup or on the climax itself?', 'Preferences & Pleasure'),
('What sensation — temperature, texture, pressure — turns you on the most?', 'Preferences & Pleasure'),

-- ===== COMMUNICATION & TRUST (25) =====
('How comfortable are you with telling me exactly what you want during sex?', 'Communication & Trust'),
('Is there anything about our sex life you have been wanting to bring up but have not?', 'Communication & Trust'),
('How do you feel about the way we communicate during intimacy — is it enough?', 'Communication & Trust'),
('What could I do or say that would make you feel safer to be vulnerable with me sexually?', 'Communication & Trust'),
('Do you feel like I listen well when you tell me what you like?', 'Communication & Trust'),
('How would you prefer I tell you if something does not feel good in the moment?', 'Communication & Trust'),
('Is there a signal or word we should have if either of us wants to pause?', 'Communication & Trust'),
('What makes you feel most respected during intimacy?', 'Communication & Trust'),
('Do you ever feel pressure to perform or to be a certain way during sex?', 'Communication & Trust'),
('How can I better check in with you during sex without breaking the mood?', 'Communication & Trust'),
('What does enthusiastic consent look like and feel like to you?', 'Communication & Trust'),
('Is there something about your body or sexuality that you feel self-conscious about?', 'Communication & Trust'),
('How can I help you feel more confident and desired?', 'Communication & Trust'),
('What role does emotional trust play in how much you enjoy physical intimacy?', 'Communication & Trust'),
('Are there topics around sex you find harder to talk about than others?', 'Communication & Trust'),
('How do you feel when I give you feedback about what feels good?', 'Communication & Trust'),
('Do you feel like we have equal say in what happens in our sex life?', 'Communication & Trust'),
('What is the best way for me to let you know I am in the mood?', 'Communication & Trust'),
('How do you feel about discussing past sexual experiences openly?', 'Communication & Trust'),
('Is there a way I could initiate that makes you feel more wanted?', 'Communication & Trust'),
('What do you need from me after sex to feel connected and cared for?', 'Communication & Trust'),
('How do you feel about our level of openness when it comes to intimacy?', 'Communication & Trust'),
('Have you ever held back a request because you were worried how I would react?', 'Communication & Trust'),
('What would make our post-sex conversations feel more natural?', 'Communication & Trust'),
('If you could change one thing about how we talk about sex, what would it be?', 'Communication & Trust'),

-- ===== INTIMACY & CONNECTION (25) =====
('What makes you feel most emotionally connected to me during sex?', 'Intimacy & Connection'),
('How important is cuddling and physical closeness after sex for you?', 'Intimacy & Connection'),
('What is the difference between having sex and making love for you?', 'Intimacy & Connection'),
('When do you feel most desired by me?', 'Intimacy & Connection'),
('What non-sexual physical touch during the day makes you feel closest to me?', 'Intimacy & Connection'),
('How does our emotional connection affect the quality of our physical intimacy?', 'Intimacy & Connection'),
('What does aftercare look like for you — what do you need after being intimate?', 'Intimacy & Connection'),
('Do you feel like sex brings us closer, or is closeness what leads to great sex?', 'Intimacy & Connection'),
('What is something I do outside the bedroom that makes you want me more?', 'Intimacy & Connection'),
('How do you feel about maintaining eye contact and being fully present during sex?', 'Intimacy & Connection'),
('What role does laughter play in our sex life — is it welcome?', 'Intimacy & Connection'),
('What was a time our intimacy felt especially deep and meaningful?', 'Intimacy & Connection'),
('How do you feel about skin-to-skin contact without any sexual expectation?', 'Intimacy & Connection'),
('What helps you transition from the stress of daily life to feeling intimate?', 'Intimacy & Connection'),
('Do you feel like our non-sexual intimacy is strong enough to support our sexual connection?', 'Intimacy & Connection'),
('What kind of compliments during sex make you feel most loved?', 'Intimacy & Connection'),
('How important is it to you that we are both fully present and not distracted?', 'Intimacy & Connection'),
('What ritual or habit before sex helps you feel more bonded with me?', 'Intimacy & Connection'),
('How do you feel about falling asleep still physically touching after sex?', 'Intimacy & Connection'),
('What does vulnerability during sex look like to you?', 'Intimacy & Connection'),
('When have you felt the deepest sense of trust with me during intimacy?', 'Intimacy & Connection'),
('How does physical intimacy affect your mood and energy the next day?', 'Intimacy & Connection'),
('What is the emotional difference between planned intimacy and spontaneous?', 'Intimacy & Connection'),
('What small acts of physical affection during the day charge your desire for me?', 'Intimacy & Connection'),
('How do you feel about sharing silence together after being intimate?', 'Intimacy & Connection'),

-- ===== EXPLORATION (25) =====
('Is there something new you have been curious about trying together?', 'Exploration'),
('How do you feel about incorporating toys or accessories into our intimacy?', 'Exploration'),
('Would you ever be interested in reading or watching something together to get inspired?', 'Exploration'),
('What is a position or technique you have heard about and want to explore?', 'Exploration'),
('How do you feel about trying intimacy in a completely new location?', 'Exploration'),
('Would you enjoy a night where one person is fully in charge of the experience?', 'Exploration'),
('How do you feel about blindfolds, restraints, or sensory play?', 'Exploration'),
('Is there a type of massage — like tantric or sensual — you would want to learn together?', 'Exploration'),
('Would you be open to taking an intimacy course or workshop as a couple?', 'Exploration'),
('How do you feel about introducing food, ice, or temperature play?', 'Exploration'),
('Would you enjoy planning a themed intimate evening together?', 'Exploration'),
('How do you feel about sexting or sending intimate messages during the day?', 'Exploration'),
('Is there a book about intimacy you would want to read together?', 'Exploration'),
('Would you be interested in trying a longer session with no goal other than exploration?', 'Exploration'),
('How do you feel about trying different types of music or lighting during sex?', 'Exploration'),
('Would you enjoy mutual self-pleasure as a shared experience?', 'Exploration'),
('Is there something from early in our relationship you would want to revisit and try again?', 'Exploration'),
('How do you feel about shower or bath intimacy?', 'Exploration'),
('Would you be open to a date night that is specifically designed to end in the bedroom?', 'Exploration'),
('How do you feel about giving each other instructions or guided touch?', 'Exploration'),
('Would you like us to each share one new thing we want to try, no judgment?', 'Exploration'),
('How do you feel about extended foreplay as the main event rather than a warmup?', 'Exploration'),
('Would you be open to creating a yes-no-maybe list together?', 'Exploration'),
('Is there a new way to be physically intimate that does not involve intercourse you would want to try?', 'Exploration'),
('How do you feel about recreating a particularly good sexual experience we have had?', 'Exploration'),

-- ===== BOUNDARIES & COMFORT (20) =====
('What are your hard boundaries that I should always respect?', 'Boundaries & Comfort'),
('Is there anything we have tried that you would rather not do again?', 'Boundaries & Comfort'),
('How do you feel about the pace at which we try new things?', 'Boundaries & Comfort'),
('Is there anything I do during sex that you tolerate rather than enjoy?', 'Boundaries & Comfort'),
('What helps you feel safe enough to say no or stop?', 'Boundaries & Comfort'),
('How do you feel about discussing boundaries before trying something new?', 'Boundaries & Comfort'),
('Is there a time of day or situation where you would prefer not to be intimate?', 'Boundaries & Comfort'),
('How do you feel about your body during sex, honestly?', 'Boundaries & Comfort'),
('What makes the difference between feeling pushed and feeling encouraged to try something?', 'Boundaries & Comfort'),
('Is there a topic related to sex that feels off-limits for you?', 'Boundaries & Comfort'),
('How important is privacy about our intimate life to you?', 'Boundaries & Comfort'),
('What would you want me to do if I could tell you were not fully into it?', 'Boundaries & Comfort'),
('Have your boundaries changed over the course of our relationship?', 'Boundaries & Comfort'),
('Is there something you once said yes to but now realize was not really a yes?', 'Boundaries & Comfort'),
('How do you feel about the conversation around protection and sexual health?', 'Boundaries & Comfort'),
('What does it look like when you are genuinely enthusiastic versus just going along?', 'Boundaries & Comfort'),
('How would you want me to react if you needed to stop in the middle of things?', 'Boundaries & Comfort'),
('Is there a part of your body you feel sensitive about being touched or seen?', 'Boundaries & Comfort'),
('What helps you recover emotionally if an intimate experience does not go well?', 'Boundaries & Comfort'),
('How can we make trying new things feel safe rather than pressured?', 'Boundaries & Comfort'),

-- ===== DRIVE & DESIRE (25) =====
('What usually triggers your desire for sex — physical cues, emotional closeness, or something else?', 'Drive & Desire'),
('How do you feel about the current frequency of our sex life?', 'Drive & Desire'),
('What time of day do you tend to feel most in the mood?', 'Drive & Desire'),
('What kills your sex drive faster than anything?', 'Drive & Desire'),
('What is something non-sexual that makes you feel really turned on?', 'Drive & Desire'),
('How does stress, sleep, or health affect your desire for intimacy?', 'Drive & Desire'),
('Do you experience desire spontaneously or does it build gradually with the right cues?', 'Drive & Desire'),
('What can I do during the day to increase the chances you will want intimacy later?', 'Drive & Desire'),
('How do you feel about initiating sex — is it something you enjoy or find awkward?', 'Drive & Desire'),
('What is the difference between wanting sex and wanting closeness for you?', 'Drive & Desire'),
('How do you feel when I turn down your advances — and how can I do it more gently?', 'Drive & Desire'),
('What role does anticipation play in building your desire?', 'Drive & Desire'),
('How do you feel about scheduling intimacy versus keeping it spontaneous?', 'Drive & Desire'),
('Is there a season, hormone cycle, or life phase that affects your desire the most?', 'Drive & Desire'),
('What is the most effective way I could seduce you?', 'Drive & Desire'),
('How do you feel when we go through a dry spell — does it worry you or feel natural?', 'Drive & Desire'),
('What kind of physical affection throughout the day makes you want more later?', 'Drive & Desire'),
('Do you ever feel desire but not act on it? What holds you back?', 'Drive & Desire'),
('How do you feel about me expressing my desire for you openly and often?', 'Drive & Desire'),
('What is the biggest turn-on for you that I might not know about?', 'Drive & Desire'),
('How do you feel about our balance of who initiates?', 'Drive & Desire'),
('What helps you get out of your head and into your body during intimacy?', 'Drive & Desire'),
('Are there external factors — like exercise, music, or wine — that boost your desire?', 'Drive & Desire'),
('What is the single quickest way to get you in the mood?', 'Drive & Desire'),
('How would you describe your ideal sexual rhythm for a typical week?', 'Drive & Desire'),

-- ===== ROMANCE & FOREPLAY (20) =====
('What is the most romantic buildup to sex we have ever had?', 'Romance & Foreplay'),
('How long do you wish foreplay lasted ideally?', 'Romance & Foreplay'),
('What kind of setting — candles, music, darkness — turns you on the most?', 'Romance & Foreplay'),
('What is the sexiest thing I have ever said to you?', 'Romance & Foreplay'),
('How do you feel about slow dancing as a form of foreplay?', 'Romance & Foreplay'),
('What is your ideal amount of flirting and teasing before things get physical?', 'Romance & Foreplay'),
('Do you enjoy being undressed slowly, or is there something hotter about urgency?', 'Romance & Foreplay'),
('What kind of kiss signals to you that things are about to heat up?', 'Romance & Foreplay'),
('How do you feel about a full-body massage before sex?', 'Romance & Foreplay'),
('What scent or perfume on me makes you feel most attracted?', 'Romance & Foreplay'),
('Is there a type of date night that always ends in great sex for us?', 'Romance & Foreplay'),
('How do you feel about anticipation — like a text earlier in the day promising what is coming?', 'Romance & Foreplay'),
('What is the best way for me to set the mood?', 'Romance & Foreplay'),
('Do you enjoy neck kisses, ear whispers, or something else as a first move?', 'Romance & Foreplay'),
('How important is ambiance — lighting, temperature, cleanliness — for you?', 'Romance & Foreplay'),
('What part of getting ready for each other do you enjoy the most?', 'Romance & Foreplay'),
('How do you feel about taking a shower or bath together before being intimate?', 'Romance & Foreplay'),
('What makes you feel most seduced versus just aroused?', 'Romance & Foreplay'),
('What is the difference between a regular night and a night that feels electric?', 'Romance & Foreplay'),
('If you could design the perfect lead-up to an incredible night together, what would it include?', 'Romance & Foreplay'),

-- ===== GROWTH & DISCOVERY (20) =====
('How has your sexuality evolved since we have been together?', 'Growth & Discovery'),
('Is there something about your own body or pleasure that you are still discovering?', 'Growth & Discovery'),
('What is something you enjoy now that you never thought you would?', 'Growth & Discovery'),
('How has your confidence in the bedroom changed over time?', 'Growth & Discovery'),
('What has being with me taught you about your own desires?', 'Growth & Discovery'),
('Is there something you want to understand better about your own sexuality?', 'Growth & Discovery'),
('How has your view of intimacy changed from your twenties to now?', 'Growth & Discovery'),
('What is a sexual experience with me that helped you grow?', 'Growth & Discovery'),
('Is there a misconception about sex you used to believe but have outgrown?', 'Growth & Discovery'),
('How do you feel about your orgasms — is there something you want to explore further?', 'Growth & Discovery'),
('What is a part of your sexual identity that you are still learning about?', 'Growth & Discovery'),
('How has communication about sex gotten easier or harder as our relationship has matured?', 'Growth & Discovery'),
('What would you want to learn about tantric or mindful intimacy?', 'Growth & Discovery'),
('Is there an area of intimacy where you feel we have grown the most together?', 'Growth & Discovery'),
('What is something you are proud of about how our sex life has developed?', 'Growth & Discovery'),
('How do you feel about aging and how it might change our intimacy?', 'Growth & Discovery'),
('What is a lesson from a past experience that makes our connection better now?', 'Growth & Discovery'),
('If you could go back and tell your younger self one thing about sex, what would it be?', 'Growth & Discovery'),
('What does a thriving, evolving sex life look like to you over the next ten years?', 'Growth & Discovery'),
('How do you want us to keep growing sexually as a couple?', 'Growth & Discovery'),

-- ===== SATISFACTION & REFLECTION (20) =====
('On a scale of one to ten, how satisfied are you with our sex life right now?', 'Satisfaction & Reflection'),
('What is the single best sexual experience we have had together?', 'Satisfaction & Reflection'),
('Is there something missing from our intimacy that you have been thinking about?', 'Satisfaction & Reflection'),
('What do you think we do really well together in bed?', 'Satisfaction & Reflection'),
('If you could change one thing about our sex life starting tonight, what would it be?', 'Satisfaction & Reflection'),
('How do you feel after we are intimate — energized, relaxed, emotional, or something else?', 'Satisfaction & Reflection'),
('What percentage of the time do you feel fully satisfied after sex?', 'Satisfaction & Reflection'),
('What is one thing I started doing that dramatically improved our intimacy?', 'Satisfaction & Reflection'),
('Do you feel like we prioritize our sex life enough?', 'Satisfaction & Reflection'),
('What was a time you felt truly worshipped during sex?', 'Satisfaction & Reflection'),
('How do you feel about how much effort we both put into our physical connection?', 'Satisfaction & Reflection'),
('What is something we used to do that you wish we would bring back?', 'Satisfaction & Reflection'),
('Do you feel like you can be your full, authentic sexual self with me?', 'Satisfaction & Reflection'),
('What was a recent intimate moment that left a lasting impression on you?', 'Satisfaction & Reflection'),
('How often do you think about our sex life during the day?', 'Satisfaction & Reflection'),
('Is there an imbalance in our intimacy that you think we should address?', 'Satisfaction & Reflection'),
('What would make you feel like our sex life is truly exceptional?', 'Satisfaction & Reflection'),
('How do you feel about the variety in our sexual routine?', 'Satisfaction & Reflection'),
('What is one small adjustment that could have a big impact for you?', 'Satisfaction & Reflection'),
('If our sex life had a progress report, what would the highlights and areas for improvement be?', 'Satisfaction & Reflection'),

-- ===== PLAYFULNESS & SPONTANEITY (20) =====
('What is the most unexpected place you would want to be intimate with me?', 'Playfulness & Spontaneity'),
('How do you feel about spontaneous intimacy in the middle of the day?', 'Playfulness & Spontaneity'),
('Would you enjoy a game where we take turns choosing what happens next?', 'Playfulness & Spontaneity'),
('What would happen if we flipped a coin to decide who leads tonight?', 'Playfulness & Spontaneity'),
('How do you feel about playful wrestling or physical games that lead to something more?', 'Playfulness & Spontaneity'),
('Would you enjoy a dare jar filled with intimate challenges?', 'Playfulness & Spontaneity'),
('What is the boldest sexual thing you have ever done?', 'Playfulness & Spontaneity'),
('How would you react if I surprised you with something spontaneous tonight?', 'Playfulness & Spontaneity'),
('What is a fun way we could make a boring evening suddenly exciting?', 'Playfulness & Spontaneity'),
('Would you enjoy a strip version of a game we already play?', 'Playfulness & Spontaneity'),
('How do you feel about spontaneous kissing that clearly signals more is coming?', 'Playfulness & Spontaneity'),
('What is the most fun we have ever had during sex?', 'Playfulness & Spontaneity'),
('If we played truth or dare right now with only intimate options, what would you pick first?', 'Playfulness & Spontaneity'),
('How do you feel about laughing during sex — does it add or distract?', 'Playfulness & Spontaneity'),
('Would you enjoy surprise love notes describing what I want to do with you later?', 'Playfulness & Spontaneity'),
('What is a spontaneous moment of desire you remember vividly?', 'Playfulness & Spontaneity'),
('How do you feel about me surprising you with a new outfit or accessory?', 'Playfulness & Spontaneity'),
('Would you enjoy planning a secret intimate surprise for each other on the same night?', 'Playfulness & Spontaneity'),
('What is the funniest thing that has ever happened during sex for us?', 'Playfulness & Spontaneity'),
('If we made a pact to be spontaneous once a week, what would your first move be?', 'Playfulness & Spontaneity')

ON CONFLICT DO NOTHING;
